#pragma once

#include <cstddef>

/** Build-time embedded copy of src/sa_params.txt (generated by xxd). */
extern const unsigned char src_sa_params_txt[];
extern const unsigned int src_sa_params_txt_len;
